trigger:
- main

stages:
- stage: Provision
  jobs:
  - job: Linux
    pool: local-agent-pool
    steps:
    - script: |
        python3 python/network.py
        python3 python/storage.py
        python3 python/vmss.py

  - job: Windows
    pool: windows-agent-pool
    steps:
    - powershell: |
        .\dsc\windows-baseline.ps1
