
trigger:
- main

pool:
  name: local-agent-pool

steps:
- script: |
    echo "ğŸ“¦ Installing Dependencies"
    python3 -m pip install --upgrade pip
    pip3 install -r requirements.txt

    echo "ğŸŒ Running Network automation"
    python3 python/network.py

    echo "ğŸ’¾ Running Storage automation"
    python3 python/storage.py

    echo "ğŸš€ Running VMSS automation"
    python3 python/vmss.py
  displayName: "Provision Azure Enterprise Platform"
